### ISSUE TITLE
Roadmap Tasks priorization/ packaging

### ISSUE THREAD

**Issue by joralgra** [joralgra/wordleBOT#1]
Would be great to define a V1.0 feature specification fot the redacted tasks at README.md

- [ ] Levenshtein distance for base cases
- [ ] FIX repeated characters on the same word.
- [ ] Provide base words for the game first word iteration.
  - [ ] Ranking of best 10 words
  - [ ] Feeling lucky (Providing one complete random word)
  - [ ] Need a challenge (Providing one of the worst 10% words)
- [ ] Add ENGLISH! (Just need data that needs to share the /data/spanish.txt format)
- [ ] Missing verb conjugations inside /data/spanish.txt (Can be used but not for the final word(?))
- [ ] Improved help/instructions, make it more visual
- [ ] Make a usable UI instead of console application
- [ ] Game state visualization improvement
- [ ] Game state CRUD
- [ ] Add other Wordle game modes
- [ ] Get game state from the wordle webpage.
- [ ] Game theory IA training ... Win % for each turn

And add them as "detailed" Issues
